networks:
  ledger-test:
    name: ledger-test

services:
  postgres:
    container_name: postgres
    image: "postgres:17-alpine"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
      PGDATA: /data/postgres
    networks:
      - ledger-test

  ledger:
    image: "ghcr.io/formancehq/ledger:${LEDGER_VERSION}"
    healthcheck:
      test: [ "CMD", "wget", "http://127.0.0.1:3068/_info", "-O", "-", "-q" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:3068
    environment:
      POSTGRES_URI: "postgresql://ledger:ledger@postgres/ledger?sslmode=disable"
    networks:
      - ledger-test
    env_file:
      - .env
